#!/bin/sh

get_staged_files() {
	git diff --name-only --cached \
		| grep unbrake-api \
		| grep .py \
		| sed -e 's@unbrake-api/@@g'
}

run_command(){
	echo -n "Running $(basename $1)..."
	get_staged_files > $tmpStagedFiles

	if [ -s $tmpStagedFiles ]; then
		xargs $* &> $tmpOutputFile

		if [ $? = 0 ]; then
			echo -e " \033[0;32mOK!\033[0m"
		else
			echo -e " \033[0;31mFAILED!\033[0m\n"
			cat $tmpOutputFile
			echo "\033[0;31mSome check failed :(\033[0m"
			echo -e "\033[0;33mHave you tried to rebuilding the image? Try look the tool documentation as well!\033[0m"
			exit 1
		fi
	else
		echo -e "\nThere's no staged python file to be checked on API..."
		exit 0
	fi
}

source scripts/scripts_environments
cd $backendFolder

echo -e "\n=====================================================================-----"
echo "You're almost committing!!! Just a second, while I run_command some checks and fixes..."
echo -e "==========================================================================\n"

run_command autopep8 -i -a -a
run_command flake8
run_command pylint

rm -rf $tmpOutputFile
echo -e "\n\033[0;32mCool! All checks succeeded! Commiting...\033[0m"
