#!/bin/sh

gitFolder="$(git rev-parse --show-toplevel)"
imageName="unbrake_backend_development"  # compose project name + service name
backendFolder="$gitFolder/unbrake-api"
tmpFile="/tmp/unbrake_hook_log"

run(){
	echo -n "Running $(basename $1)..."
	$* > $tmpFile
	if [ $? = 0 ]; then
		echo -e " \033[0;32mOK!\033[0m"
	else
		echo -e " \033[0;31mFAILED!\033[0m\n"
		cat $tmpFile
		echo "Some check failed :("
		echo -e "\033[0;33mHave you tried to rebuilding the image? Try look the tool documentation as well!\033[0m"
		exit 1
	fi
}

cd $backendFolder
echo -e "\n=====================================================================-----"
echo "You're almost committing!!! Just a second, while I run some checks and fixes..."
echo -e "==========================================================================\n"

run flake8 .
run pylint *

echo -e "\n\033[0;32mCool! All checks succeeded! Commiting...\033[0m"
