"""
=============================
SETTINGS USED FOR PRODUCTION
=============================

Django settings for unbrake_api project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from unbrake_api.settings import (
    BASE_DIR,
    INSTALLED_APPS,
    MIDDLEWARE,
    GRAPHENE,
    AUTHENTICATION_BACKENDS,
    AUTH_PASSWORD_VALIDATORS,
    TEMPLATES,
    WSGI_APPLICATION,
    TEMPLATES,
    STATIC_URL,
    ROOT_URLCONF,
)


def get_secret(secret_name, filename):
    '''
    Take first line of secret file
    '''
    try:  # On run
        secret_path = os.path.join('/run/secrets', secret_name)
        secret_file = open(secret_path)
    except FileNotFoundError:
        try:  # On build
            secret_path = os.path.join('./secrets', filename)
            secret_file = open(secret_path)
        except FileNotFoundError:
            raise FileNotFoundError(
                f"""
                ===================================================================
                '{secret_name}' secret not found.
                ===================================================================
                """
            )

    return secret_file.readline().strip('\n')


SECRET_KEY = get_secret('api-django-secret-key', 'API_DJANGO_SECRET_KEY')

DEBUG = False

CSRF_COOKIE_SECURE = True

SESSION_COOKIE_SECURE = True

ALLOWED_HOSTS = ['*']  # Check later

CORS_ORIGIN_ALLOW_ALL = False

CORS_ORIGIN_WHITELIST = (
    'unbrake-hom.ml', 'unbrake.ml', 'api.unbrake-hom.ml'
)

CSRF_TRUSTED_ORIGINS = (
    'unbrake-hom.ml', 'unbrake.ml', 'api.unbrake-hom.ml'
)

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True

ROOT_URLCONF = 'unbrake_api.urls'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'unbrake',
        'USER': 'unbrake',
        'PASSWORD': get_secret('postgres_password', 'DB_PASSWORD'),
        'HOST': 'db',
        'PORT': '5432'
    }
}
