#!/bin/sh

echo -e "\n=========================================================================="
echo "Checking everything on API..."
echo -e "==========================================================================\n"

cd /app/api/scripts

for checker in $(ls check* | grep -wv "check_all"); do
	./$checker || exit 1
done

echo -e "\n\033[0;32mCool! All checks succeeded!\033[0m"
