# Generated by Django 2.2 on 2019-05-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('is_default', models.BooleanField()),
                ('number', models.PositiveIntegerField()),
                ('time_between_cycles', models.PositiveIntegerField()),
                ('upper_limit', models.IntegerField()),
                ('inferior_limit', models.IntegerField()),
                ('upper_time', models.IntegerField()),
                ('inferior_time', models.IntegerField()),
                ('disable_shutdown', models.BooleanField()),
                ('enable_output', models.BooleanField()),
                ('temperature', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('time', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
            ],
        ),
    ]
