# Generated by Django 2.2 on 2019-05-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20190525_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
