# Generated by Django 2.2.2 on 2019-06-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_remove_config_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='temperature',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='config',
            name='time',
            field=models.FloatField(default=1.0),
        ),
    ]
