# Generated by Django 2.2 on 2019-05-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_auto_20190525_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='config',
            name='name',
        ),
    ]
