# Generated by Django 2.2.2 on 2019-06-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_remove_config_testing'),
        ('configuration', '0005_auto_20190525_2244'),
    ]

    operations = [
    ]
