# Generated by Django 2.2.2 on 2019-06-16 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_auto_20190614_0224'),
        ('configuration', '0006_merge_20190615_2234'),
    ]

    operations = [
    ]
