#!/bin/sh

gitFolder="$(git rev-parse --show-toplevel)"
imageName="$(basename $gitFolder)"_frontend  # compose project name + service name
frontendFolder="$gitFolder/../unbrake_frontend"

rm -rf $gitFolder/.git_backup \
    && cp -r $gitFolder/.git /tmp/.git_backup

# git folder volume must be /app/.git
sudo docker run \
    --rm \
    --entrypoint "/app/frontend/scripts/run_container_hook" \
    -t \
    -v "/tmp/.git_backup:/app/.git" \
    $imageName "$(basename $0)" $@

didBrake=$?
rm -rf /tmp/.git_backup
exit $didBrake
