# Generated by Django 2.2 on 2019-05-29 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('is_default', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_chanel_speed', models.IntegerField()),
                ('actual_speed', models.FloatField()),
                ('max_speed', models.FloatField()),
                ('chanel_command_pression', models.IntegerField()),
                ('actual_pression', models.FloatField()),
                ('max_pression', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transversal_selection_width', models.IntegerField()),
                ('heigth_width_relation', models.IntegerField()),
                ('rim_diameter', models.IntegerField()),
                ('sync_motor_rodation', models.IntegerField()),
                ('sheave_move_diameter', models.IntegerField()),
                ('sheave_motor_diameter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationSpeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_chanel', models.IntegerField()),
                ('tire_radius', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationVibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_chanel', models.IntegerField()),
                ('conversion_factor', models.FloatField()),
                ('vibration_offset', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_chanel', models.IntegerField()),
                ('conversion_factor', models.FloatField()),
                ('temperature_offset', models.FloatField()),
                ('calibration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration.Calibration')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationForce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_chanel', models.IntegerField()),
                ('conversion_factor', models.FloatField()),
                ('force_offset', models.FloatField()),
                ('calibration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration.Calibration')),
            ],
        ),
        migrations.AddField(
            model_name='calibration',
            name='command',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calibration.CalibrationCommand'),
        ),
        migrations.AddField(
            model_name='calibration',
            name='relations',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calibration.CalibrationRelations'),
        ),
        migrations.AddField(
            model_name='calibration',
            name='speed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calibration.CalibrationSpeed'),
        ),
        migrations.AddField(
            model_name='calibration',
            name='vibration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calibration.CalibrationVibration'),
        ),
    ]
