# Generated by Django 2.2 on 2019-05-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='is_default',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibration',
            name='name',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
