# Generated by Django 2.2 on 2019-06-10 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='testing',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='testing.Testing'),
        ),
    ]
