# Generated by Django 2.2.2 on 2019-06-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0003_remove_calibration_testing'),
        ('calibration', '0002_auto_20190525_2244'),
    ]

    operations = [
    ]
