# Generated by Django 2.2 on 2019-06-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('create_by',
                 models.CharField(
                     max_length=20)),
                ('create_date',
                 models.DateTimeField()),
            ],
        ),
    ]
