# Generated by Django 2.2 on 2019-06-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='create_date',
        ),
    ]
