# Generated by Django 2.2 on 2019-06-11 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0003_remove_calibration_testing'),
        ('configuration', '0003_remove_config_testing'),
        ('testing', '0002_remove_testing_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='calibration',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='calibration.Calibration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testing',
            name='configuration',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='configuration.Config'),
            preserve_default=False,
        ),
    ]
